version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    target-branch: main
    schedule:
      interval: weekly
      day: monday
      timezone: UTC
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - npm
    commit-message:
      prefix: deps
    groups:
      npm-minor-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: github-actions
    directory: "/"
    target-branch: main
    schedule:
      interval: weekly
      day: monday
      timezone: UTC
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: deps
    groups:
      actions:
        patterns:
          - "*"
